// This file is generated by `abot plugin install`. Do not edit.
package main

import (
	_ "github.com/itsabot/plugin_weather"
)

/*
github.com/itsabot/plugin_weather
{
	"Name": "Weather",
	"Maintainer": "Evan Tann <evan@itsabot.org>",
	"AbotVersion": 0.2,
	"Description": "Get weather reports for cities.",
	"Icon": "https://cdn.rawgit.com/itsabot/plugin_weather/master/icon.svg",
	"ID": 1
}
*/